### ISSUE TITLE
"Prelude.head: empty list" error when using the manager on Windows behind a firewall

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-manager#111]
Related: https://news.ycombinator.com/reply?id=16164541&goto=item%3Fid%3D16163769%2316164541

**Comment by 3Dcube** [comment]
I got the same error. I tried to turn off firewall, windows defender, used it with VPN connection and with the direct connection to the internet without a router, still no luck. It's probably not related to the firewall at all.

**Comment by 1600** [comment]
Same error here.

**Comment by rfunix** [comment]
+1

**Comment by hardliner66** [comment]
The link should be: https://news.ycombinator.com/item?id=16164541&goto=item%3Fid%3D16163769

**Comment by DominikPott** [comment]
+1

**Comment by ducktype** [comment]
+1

**Comment by 573** [comment]
+1

**Comment by wdanilo** [comment]
Hi guys! Try the 1.0.1 version, it should be fixed now!

**Comment by Vesnica** [comment]
@wdanilo Confirmed, ver 1.0.1 installed successfully. :+1:
