### ISSUE TITLE
Install behind proxy 

### ISSUE THREAD

**Issue by leiserfg** [luna/luna-manager#117]
I am behind a proxy and tried to install but it takes a long time, I don't know if it is using the proxy or not.

**Comment by wdanilo** [comment]
Could you please provide us with  as much detail as possible about the times, your system, its configuration and expected behavior?

**Comment by leiserfg** [comment]
Sorry, the problem only occur with the UI installer only, I did run luna-manager manually and it's works fine.

**Comment by wdanilo** [comment]
@leiserfg hmm, its almost impossible. The GUI installer just calls `luna-manager` behind the scenes. Maybe there were some network problems when you first tried? Anyway, I'll close it for now, but please re-open as you need! :)
