### ISSUE TITLE
Allow using the installer without providing mail address

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-manager#118]
It seems that our choice to always require mail address even in beta is controversial. We should relax the requirements and allow progressing without providing the mail address.

Here is related Hackernews discussion: https://news.ycombinator.com/item?id=16167240

**Comment by sylwiabr** [comment]
Luna manager is allowing you to install luna-studio without giving an e-mail. Moving to graphical installer.

**Comment by sylwiabr** [comment]
Issue moved to [luna/installer-electron #19](https://github.com/luna/installer-electron/issues/19) via [**ZenHub**](https://www.zenhub.com/)
