### ISSUE TITLE
Windows 7 Problem Installing Luna

### ISSUE THREAD

**Issue by lukagudelj** [luna/luna-manager#126]
------------------------Error----------------------------------
'powershell' is not recognized as an internal or external command,
operable program or batch file.
Received ExitFailure 1 when running
Shell command: powershell "$s=New-Object -ComObject WScript.Shell; $sc=$s.createShortcut('C:\Users\Luka\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\LunaStudio.lnk');$sc.TargetPath='C:\Program Files\LunaStudio\1.0\bin\public\luna-studio\luna-studio.exe';$sc.Save()"
---------------------------------------------------------------

-----------------System information-------------------------
Operating System: Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.171231-1547)
           System Manufacturer: Gigabyte Technology Co., Ltd.
           System Model: B85M-HD3
           BIOS: BIOS Date: 10/29/14 10:04:21 Ver: 04.06.05
           Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
           Memory: 16384MB RAM
           Available OS Memory: 16284MB RAM
           Page File: 8891MB used, 7390MB available
-----------------------------------------------------------------

**Comment by coopyey** [comment]
I had this issue during installation - you need to add powershell to your path environment variable.

[Here's a Microsoft help doc on how to modify or add to the PATH variable.](https://msdn.microsoft.com/en-us/library/office/ee537574(v=office.14).aspx)

To add powershell to your path, you should use: %windir%\system32\WindowsPowerShell\v1.0\

**Comment by wdanilo** [comment]
There is also another comment from "guyinpants":
```
it's possible that some users don't have powershell in their path for whatever reason, 
maybe change this to a full path here 
https://github.com/luna/luna-manager/blob/761a457f7d7ab1da06f041544553115ea741214e/luna-manager/src/Luna/Manager/Command/Install.hs#L205
and list powershell as a dependency or switch it out?
```
