### ISSUE TITLE
Ask user where should tmp folder be created (windows)

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-manager#148]

**Comment by wdanilo** [comment]
Why?

**Comment by sylwiabr** [comment]
Because we are doing it in `c:/tmp` (regular tmp path is too long and there are problems with MAX_PATH`) and user can have really small C partition or just don't want to have it there. There were complains about this from windows users on #general

**Comment by sylwiabr** [comment]
add `--tmp` option to pass to luna-manager
