### ISSUE TITLE
how do i uninstall this?

### ISSUE THREAD

**Issue by brandonmp** [luna/luna-manager#164]
I installed luna studio on a lark a month or two ago, but it never worked.

Today I noticed `luna-empire.exe` running on my computer. As far as I can tell this process belongs to Luna Studio, but there's no uninstaller showing up in win10 add/remove program.

I downloaded / ran `luna-manager`, but there's no indication that it's aware of the current installation & no way to uninstall it.

So: how do I remove this software?

**Comment by mikusp** [comment]
Please download a fresh installer and install newest Luna Studio. Starting from 1.0.2 we provide an uninstaller that is registered in add/remove programs. It will remove all installed versions of Luna Studio.

Let us know if you have any further issues.

**Comment by brandonmp** [comment]
thanks. installing [the windows edition ](http://packages.luna-lang.org/windows/lunaInstaller.zip) added LunaStudio to the Add / Remove Programs list, at which point I was unable to uninstall like normal.

**Comment by shengyang998** [comment]
Hi @mikusp 
How can I uninstall luna-studio on `macOS`? Is it enough by removing the `.app` file and `$PATH`? I can't find any infomation about it. I just got 1.6 beta installed.
