### ISSUE TITLE
Http failure in Windows 10 with release 1.2; must restart installer

### ISSUE THREAD

**Issue by BatmanAoD** [luna/luna-manager#171]
I got the following error trying to install release 1.2 on Windows 10:

```
Couldn't download file: https://github.com/luna/luna-studio/releases/download/1.2/luna-studio-windows-1.2.tar.gz because of: HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/luna/luna-studio/releases/download/1.2/luna-studio-windows-1.2.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
```

The orange button changed from "Install" to "Close" (without, as far as I could tell, ever going through the "Downloading" state).

After closing the installer using the button and re-running it, the download was successful. The installation itself has not yet completed.

**Comment by piotrMocz** [comment]
@BatmanAoD sory for no immediate feedback on this -- we were (are) swamped with tasks.

I don't think this issue persists, we haven't heard about any failing installations (as of release 1.5 everything seems to work as expected -- although the download and installation times are quite significant).

If it turns out to be a problem with 1.5 as well, I'll re-open.

**Comment by BatmanAoD** [comment]
@piotrMocz  ...I had actually completely forgotten that I wanted to try out Luna.

I've just successfully installed it on my current Windows 10 machine without seeing anything unusual, so it seems you are correct that the issue has been fixed. Thanks!
