### ISSUE TITLE
Windows installer does nothing

### ISSUE THREAD

**Issue by dumptruckman** [luna/luna-manager#187]
When I try to launch lunaInstaller.exe on Windows 10 Pro, windows asks for elevated permissions and then nothing else happens. I looked in my system logs to see if there were any errors reported but nothing is there either.

**Comment by sylwiabr** [comment]
@dumptruckman  can you check the newest Installer available on the website?

**Comment by dumptruckman** [comment]
Seems to be working just fine. However, Windows did report the publisher was unknown. Not sure what you're suppose to do about that but figured I'd let you know.

**Comment by iamrecursion** [comment]
Thanks for the report! We’re working on getting a certificate to sign the installer which should alleviate that kind of problem. :)
