### ISSUE TITLE
Luna-develop fails on systems with no pip installed

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-manager#192]
@lunalangCI commented on [Tue Jul 24 2018](https://github.com/luna/luna-studio/issues/986)

On a clean MacOS install (10.12) running `luna-manager develop luna-studio` produces the following error:
```
Exception: error running: pip install --user -r requirements.txt
exit status: 127. exit code 127 usually means the command does not exist (in the PATH)
stderr: pyenv: pip: command not found

The `pip' command exists in these Python versions:
  3.6.2
```

**Comment by piotrMocz** [comment]
The problem here wasn't the lack of `pip`, it was the misplaced `.python-version` file (from pyenv). This is fixed.

**Comment by piotrMocz** [comment]
The problem here wasn't the lack of `pip`, it was the misplaced `.python-version` file (from pyenv). This is fixed.
