### ISSUE TITLE
Insufficient quoting in luna-shell script

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-manager#193]
@lunalangCI commented on [Wed Jul 25 2018](https://github.com/luna/luna-studio/issues/989)

This happened when running `make-package`:
```

Running package build script

luna-shell.sh: line 2: export: `Fusion.app/Contents/Public:/Users/mac/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/VMware': not a valid identifier
luna-shell.sh: line 2: export: `Fusion.app/Contents/Public': not a valid identifier
```
Which may be caused by us not quoting the PATH(s) correctly.

**Comment by maedoc** [comment]
I ran into this on Windows during uninstall, where a number of errors were listed because, it seems paths aren't being quoted.  I'll try to cook up a fix and send a PR.

**Comment by piotrMocz** [comment]
I'm closing this issue: until someone stumbles upon it again, I'll consider this done and fixed.
