### ISSUE TITLE
[Windows] PC completely freezes during installation

### ISSUE THREAD

**Issue by Xh4H** [luna/luna-manager#199]
This issue has happened with both, GUI and CL installers.

I ran CLI with verbose on, and the last step I saw before this happened was [this](https://cdn.discordapp.com/attachments/403573875901726720/494594932175142912/unknown.png).

It never ended up copying a single file in the desired folder (or at least none that I could see?).

Version: the one you released today (26/09/2018 with luna 1.5).

**Comment by PurgePJ** [comment]
Update: A kind member from the Discord Server suggested turning the AV off since they always scan every single file. Fortunately the PC didn't freeze anymore.

I will test tomorrow if it was the root of the issue or not.

**Comment by mwu-tow** [comment]
Closing as external (behavior related to AV software) and not reproducible.
