### ISSUE TITLE
C:\tmp is not a proper temporary directory

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-manager#207]
The proper temporary directory in Windows 10 is `C:\Users\username\AppData\Local\Temp`. This should not be hardcoded though, function like http://hackage.haskell.org/package/directory-1.3.3.1/docs/System-Directory.html#v:getTemporaryDirectory looks reliable enough.

I suspect that C:\tmp choice might have been an attempt to avoid MAX_PATH limitation… but well, it still there (#205), it is the tooling that needs fixing.

**Comment by sylwiabr** [comment]
Since we are using 7zip in manager we can fix this one

**Comment by piotrMocz** [comment]
This should've been fixed by: https://github.com/luna/luna-manager/pull/213
