### ISSUE TITLE
ssl certificate support for packages.luna-lang.org

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-manager#209]
When using packages uploaded to our luna-packages S3 bucket, they should be available under  packages.luna-lang.org hostname. However, using such hostname in urls causes issues, as apparently it is not supported by our ssl certificate (or however this works). 

Consider:
https://s3-us-west-2.amazonaws.com/packages-luna/dataframes/windows-package-base.7z
I can download this file with browser or curl without any issues

https://packages.luna-lang.org/dataframes/windows-package-base.7z
I cannot download this with `curl`, example:
```
curl: (51) SSL: no alternative certificate subject name matches target host name 'packages.luna-lang.org'
Package.hs: callProcess: curl "-fSL" "-o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\-676e47f744c719ce\\libs-dev-v140.7z" "https://packages.luna-lang.org/dataframes/libs-dev-v140.7z" (exit 51): failed
```

Also Firefox (and likely other browser) warn about the connection not being secure and blocks it by default.

**Comment by sylwiabr** [comment]
@mwu-tow can you check if it is working now?

**Comment by mwu-tow** [comment]
@sylwiabr I seems that it is working now correctly. :)
