### ISSUE TITLE
Support for adding external Luna packages when building a new package

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-manager#211]
The packages will be copied into the `env` folder, next to `Std`. This will ensure they are discoverable by `luna`.

**Comment by mikusp** [comment]
Current status: there is a `--external_package` parameter for deploy scripts that will include given package into Luna Studio. Right now only our windows machine can include dataframes. Relocatable package for Linux is done, but it would require changes in deploy scripts/manager to properly include it.
